name: examen1b2_flutter
description: Aplicacion sencilla para gestionar campanas de vacunacion canina y felina.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.5.0
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.0


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.


flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true
  web: false

  android_12:
    color: "#ffffff"
    image: assets/logo.png